src/lib/prompts/prompt-types.ts
=> feat: :sparkles: Persist prompts on focus out

README.md, package.nls.json, package.nls.zh-cn.json, src/lib/commit-message.ts, src/lib/commitlint.ts, src/lib/prompts.ts
=> supports commitlint rules about commit header

package.json, src/extension.ts, src/lib/localize.ts, src/lib/prompts.ts, yarn.lock
=> feat: :globe_with_meridians: support conventional commit types in chinese

.vscode/settings.json
Set the emojiFormat as `code` in the workspace.
Close #54
=> ci: :wrench: set emojiFormat to code

.github/workflows/release.yml
=> fix(actions): :bug: fix the pushing commit before the publishing

.github/workflows/release.yml, CHANGELOG.md, package.json
Ref: https://github.com/vivaxy/vscode-conventional-commits/actions/runs/641361649
=> chore(release): :rewind: revert the v1.16.1 commit

.github/workflows/test-release.yml
=> test(actions): :construction_worker: test the -p option and add nodejs setup

.github/workflows/test-release.yml
=> test(actions): :bug: fix missing publish

.github/workflows/release.yml
@yi-Xu-0100 It's better to reuse npm scripts.
I think it's a small update. I'll merge it myself.
=> build: :construction_worker: update ci command to `yarn deploy`

.github/workflows/build.yml, .github/workflows/release.yml
Create the `vsix` for the test if the code changed.
=> ci(actions): :construction_worker: add build for bate version

.github/workflows/build.yml
1. fix name for works and steps
2. update name for artifact
=> ci(actions): :hammer: update build action

.github/workflows/build.yml
It will add `.zip` automatically.
=> ci(actions): :bug: fix the artifact name

.github/workflows/build.yml
=> ci(actions): :pencil2: fix typo mistake

.github/workflows/build.yml, .github/workflows/post-build.yml
1. add output job for the build action.
2. add post-build action to delete the label and comment on the PR.
=> ci(build): :zap: add post-build action

src/extension.ts, src/lib/commitlint.ts, src/lib/conventional-commits.ts, src/lib/editor/provider.ts, src/lib/localize.ts, src/lib/output.ts, src/lib/prompts/prompt-types.ts, src/modules/@commitlint/load/lib/load.js, src/modules/@commitlint/load/lib/utils/load-plugin.js, src/modules/@commitlint/resolve-extends/lib/index.js, src/modules/import-fresh/index.js, src/modules/resolve-global/index.js
1. add more messages to make the output more clear.
2. use `__non_webpack_require__` to instead of `eval('require')`.
Ref #102
=> perf(log): :zap: improve the log output

src/lib/commit-message.ts, src/lib/prompts.ts
=> fix(commit-message): :bug: fix the prompt context retaining issue

.github/workflows/build.yml, .github/workflows/post-build.yml
=> ci(build): :bug: fix no access permission

.github/workflows/build.yml
ref: https://github.com/vivaxy/vscode-conventional-commits/actions/runs/772744380
=> ci(build): :bug: fix grammatical errors

.github/workflows/post-build.yml
ref: https://github.com/vivaxy/vscode-conventional-commits/actions/runs/772762216
=> ci(post-build): :bug: fix comment condition

package.json
update vscode engines to ^1.44.0
ref: #141
=> feat(deps): :arrow_up: update vscode engines

.github/workflows/release.yml
=> ci(release): :green_heart: publish to the Open VSX Registry

src/lib/prompts/prompt-types.ts, src/lib/prompts/quick-pick.ts
=> feat: :sparkles: add confirm button

src/lib/prompts/quick-pick.ts
=> fix: :lipstick: default activeItem to be the top choice

.github/workflows/build.yml, .github/workflows/prepare-release.yml, .github/workflows/release.yml
=> ci(node): :arrow_up: update node version to v14 in action

src/lib/prompts.ts
=> fix: resolve `skip ci` in none-english version

src/lib/conventional-commits.ts
=> fix: mark `_rootUri` as optional property

src/lib/conventional-commits.ts
Ref: 
https://github.com/DonJayamanne/gitHistoryVSCode/blob/75575aa03d03a06a2b901944d65a0f58f4875e02/src/commandHandlers/gitHistory.ts#L62-L70
=> fix: get `rootUri` from `VSCodeGit.Repository`

package.json, yarn.lock
Update vsce to latest version. See in https://github.com/microsoft/vscode-vsce/issues/799
=> fix: :bug: update vsce to @vscode/vsce

tsconfig.json
Relates to #336 - As GitHub Actions do currently not work, this could be a possible fix for:
https://github.com/vivaxy/vscode-conventional-commits/actions/runs/9725065319
=> Compiler fix
